### PR TITLE
Use hex utilities from MOOSE

### PR DESCRIPTION
**Pull request by GiudGiud**
name slightly changed. The Cardinal name was slightly better imo but new name facilitated integration

### CODE REVIEW

**Comment by GiudGiud** [comment]
Looks like unit testing is hosed. I think this is tied to the moose submodule update?

**Comment by aprilnovak** [comment]
Did all of the unit tests which were in Cardinal get moved over into MOOSE? I see the `GeometryUtilityTest.C`, but not the `HexagonalUtilityTest.C` (or similar name) in https://github.com/idaholab/moose/tree/next/unit/src. 

I am not sure why it's failing to build, does something need to be adjusted in the unit Makefile?

**Comment by GiudGiud** [comment]
The hexagonal stuff moved to the reactor module, while the GeometryUtil moved to the framework. 

I ll double check in an hour

**Comment by GiudGiud** [comment]
See https://github.com/idaholab/moose/blob/next/modules/reactor/unit/src/HexagonalLatticeTest.C

I dont know about unit tests. Nothing obvious to me so far

**Comment by GiudGiud** [comment]
Should work now.
@aprilnovak do you accept devel branches for the moose submodule or should I re-update the module once we have a 'master' merge

**Comment by aprilnovak** [comment]
Thanks @GiudGiud! I typically do devel updates, not for any particular reason though. So this should be good to go

**Pull request merged**
